### ISSUE TITLE
py::enum_'s `__int__` and `__hash__` do not behave correctly when the underlying type of enum class is char

### ISSUE THREAD

**Issue by Vigilans** [pybind/pybind11#1331]
## Issue description

I am exposing an enum class to python, and this is my code:
``` cpp
// enum class to expose
enum class Player : char { 
    White = -1, None = 0, Black = 1 
};
```

```cpp
// pybind11 wrapper
py::enum_<Player>(mod, "Player", "Gomoku player types")
    .value("white", Player::White)
    .value("none",  Player::None)
    .value("black", Player::Black)
    //.def(py::init<int>()) this line run into another error
    .def("__int__",   [](Player p) { return static_cast<int>(p); })
    .def("__float__", [](Player p) { return static_cast<double>(p); })
    .def("__hash__",  [](Player p) { return static_cast<int>(p); })
    .def("__neg__",   [](Player p) { return -p; })
    .def_static("calc_score", [](Player p, Player w) { return getFinalScore(p, w); });

```

As I was testing the module in python, I ran into such a strange issue:
```bash
>>> int(Player.black)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __int__ returned non-int (type str)

>>> hash(Player.black)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __hash__ method should return an integer

>>> float(Player.black)
1.0
```
In fact, similar issues have occurred when I pass the `py::arithmetic()` extra parameter to py::enum_.

Then I checked the inner member functions and discovered these:
```bash
>>> Player.black.__int__()
'\x01'
>>> Player.white.__int__()
'ÿ'
>>> Player.white.__hash__()
'ÿ'
```

So, why does a `static_cast<int>` resulted in a str in python?

**Intuitively,  I change the underlying type of `enum class Player` from `char` to `int`, and:**
```bash
>>> Player.black.__int__()
1
>>> Player.white.__hash__()
-1
>>> int(Player.none)
0
```
Thus, it is the underlying type `char` of `enum class player` that causes all these bugs.

**Comment by Vigilans-Yea** [comment]
BTW, when defining the enum class:
```cpp
// pybind11 wrapper
py::enum_<Player>(mod, "Player", "Gomoku player types")
    .value("white", Player::White)
    .value("none",  Player::None)
    .value("black", Player::Black)
    //.def(py::init<int>()) this line run into another error
    .def("__int__",   [](Player p) { return static_cast<int>(p); })
    .def("__float__", [](Player p) { return static_cast<double>(p); })
    .def("__hash__",  [](Player p) { return static_cast<int>(p); })
    .def("__neg__",   [](Player p) { return -p; })
    .def_static("calc_score", [](Player p, Player w) { return getFinalScore(p, w); });
```
the `def(py::init<int>())` caused another bug in compiling:

> C2440	Unable to convert “initializer list” to “Gomoku::Player”

And I don't have any idea how to solve this _(:з」∠)_……

**Comment by Vigilans-Yea** [comment]
Oh, I  have solved the bug of `py::init`...I try to pass a lambda function to `py::init` instead, and everything works fine:
```cpp
def(py::init([](int p) { return Player(p); }))`
```
Maybe the form of creating an enum `<Player(int)>` is not so identical with a constructor, and causes some conflicts...

**Comment by Vigilans-Yea** [comment]
@jagerman 

Thank you. I would love to have a try(〜￣△￣)〜
