### ISSUE TITLE
Problems trying to use cryptodome AES encryption

### ISSUE THREAD

**Issue by thepasto** [pybind/pybind11#1335]
## Issue description
Hello, 
I was trying to convert an old pure python script, beacuse i recently start to study something about c++.
I had a problem to create a new AES object, maybe it's a wrong approach, but i din't find any clue about that.

## Reproducible example code
Here's i my original python funtion:
```
def encrypt(self, text):
        bs = AES.block_size
        iv = Random.new().read(bs)
        cipher = AES.new(self.secret, AES.MODE_CFB, iv)
        encrypted = cipher.encrypt(text)
```

Here's the result:
```
void encrypt() {
		py::object py_aes = py::module::import("Cryptodome.Cipher.AES");
		py::object py_base64 = py::module::import("base64");
		py::int_ py_bs = py_aes.attr("block_size");
		py::int_ py_aesmode = py_aes.attr("MODE_CFB");
		py::object py_random = py::module::import("Cryptodome.Random");

		py::object py_rnd = py_random.attr("new")();
		py::str py_iv = py_rnd.attr("read")(py_bs);

		py::object py_cipher = py_aes.attr("new")(this->secret, py_aesmode, py_iv);
                ......
}
```
But after many tries, i always get this kind of error:

`Traceback (most recent call last):
File "<stdin>", line 1, in <module>                                                                                     
File "C:\Python27_x64\lib\site-packages\Cryptodome\Cipher\AES.py", line 200, in new                                       return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)                                              File "C:\Python27_x64\lib\site-packages\Cryptodome\Cipher\__init__.py", line 55, in _create_cipher                        return modes[mode](factory, **kwargs)                                                                                 
File "C:\Python27_x64\lib\site-packages\Cryptodome\Cipher\_mode_cfb.py", line 230, in _create_cfb_cipher                  cipher_state = factory._create_base_cipher(kwargs)                                                                    File "C:\Python27_x64\lib\site-packages\Cryptodome\Cipher\AES.py", line 100, in _create_base_cipher                       result = start_operation(c_uint8_ptr(key),                                                                            
File "C:\Python27_x64\lib\site-packages\Cryptodome\Util\_raw_api.py", line 151, in c_uint8_ptr                            raise TypeError("Object type %s cannot be passed to C code" % type(data))                                           TypeError: Object type <type 'unicode'> cannot be passed to C code`

Thanks for your help!

**Comment by XBITSwitzerland** [comment]
Have you fixed the error?

**Comment by kincody** [comment]
try using text.encode('ascii', 'ignore')
```
def encrypt(self, text):
        bs = AES.block_size
        iv = Random.new().read(bs)`
        cipher = AES.new(self.secret, AES.MODE_CFB, iv)
        encrypted = cipher.encrypt(text.encode('ascii', 'ignore'))
```

**Comment by maple-abhishek** [comment]
You may use "str(text)". This worked for me. I think we can close this Issue.
