### ISSUE TITLE
tests fail with python-3.7.3

### ISSUE THREAD

**Issue by mslacken** [pybind/pybind11#1949]
Running the tests with python 3.7.3 fail with 
Traceback (most recent call last):
  File "setup.py", line 334, in <module>
    'backend-test-tools = onnx.backend.test.cmd_tools:main',
  File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/site-packages/ptr.py", line 209, in run
    return self.run_tests()
  File "/usr/lib/python3.7/site-packages/ptr.py", line 220, in run_tests
    result_code = __import__('pytest').main()
  File "/usr/lib/python3.7/site-packages/pytest.py", line 6, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/usr/lib/python3.7/site-packages/_pytest/assertion/__init__.py", line 6, in <module>
    from _pytest.assertion import rewrite
  File "/usr/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 15, in <module>
    from typing import Dict
  File "/home/abuild/rpmbuild/BUILD/onnx-1.6.0/.eggs/typing-3.7.4.1-py3.7.egg/typing.py", line 1357, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/home/abuild/rpmbuild/BUILD/onnx-1.6.0/.eggs/typing-3.7.4.1-py3.7.egg/typing.py", line 1005, in __new__
    self._abc_registry = extra._abc_registry

There is no additional python-typing package installed.

**Comment by mslacken** [comment]
I am building against openSUSE tumbleweed/Factory which uses python 3.7.3, so the errors are not coming from a backport, the backported version to 3.5 does not show this error. As soon as Ubuntu will upgrade to python 3.7, this error will also be on ubuntu.

**Comment by molpopgen** [comment]
My system is 3.7.3:

```
python3 --version
Python 3.7.3
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Pop!_OS 19.04
Release:	19.04
Codename:	disco
```

**Comment by wjakob** [comment]
Are you sure that you are reporting a pybind11 issue here? Your backtrace shows that you appear to be building ``ONNX``, which is not related to this project in any way. I'll close this for now.
