### ISSUE TITLE
Calling del Class.field from python, when its a def_readonly_static segfaults

### ISSUE THREAD

**Issue by fried** [pybind/pybind11#2009]
## Issue description

def_readonly_static defined fields segfault when used with python delattr, Python as a safe environment it would be expected to instead see a TypeError

## Reproducible example code
```cpp
class Test {
  public:
     static const int field;
};

const int Test::field = 10;

PYBIND11_MODULE(example, m) {
   py::class_<Test>(m, "Test")
       .def_readonly_static("field", &Test::field);
}

```

```python
from example import Test
del Test.field  # BOOM
```

The relevant segfault st

```
     null-deref
     #0 0x7fe1836b55f4 in PyObject_IsInstance /home/engshare/third-party2/python/3.7/src/cpython-3.7/Objects/abstract.c:2379
     #1 0x7fe172d0634a in pybind11_meta_setattro third-party-buck/platform007/build/pybind11/f3b1ccc/include/pybind11/detail/class.h:110
```

**Comment by fried** [comment]
I'm using pybind11 2.2.1

**Comment by YannickJadoul** [comment]
Confirmed; this is still an issue on Python 3.8 with pybind11 2.5.0
