### ISSUE TITLE
Segfault with SystemExit

### ISSUE THREAD

**Issue by pavelschon** [pybind/pybind11#2063]
## Issue description

Segmentation fault when trying to extract exit code from SystemExit.

## Reproducible example code

```c++
#include <pybind11/embed.h>
#include <iostream>

namespace py = pybind11;

int main( int argc, char** argv )
{
    py::scoped_interpreter guard;

    try
    {
        py::exec("raise SystemExit(100)");
    }
    catch( const py::error_already_set& e )
    {
        std::cerr << e.what() << std::endl;

        if( e.matches(py::module::import("exceptions").attr("SystemExit")))
        {
            auto args = e.value().attr("args");

            std::cerr << "SystemExit.args = " << py::cast<std::string>(py::str(args)) << std::endl;
            std::cerr << "ExitStatus = " << py::cast<int>(args[0]) << std::endl;

            return py::cast<int>(args[0]);
        }

        return -1;
    }

    return 0;
}
```
## Output
```
SystemExit: 100

At:
  <string>(2): <module>

SystemExit.args = (100,)
ExitStatus = Segmentation fault
```
## Backtrace
```
(gdb) bt
#0  0x00007ffff7298901 in __strlen_sse2_pminub () from /lib64/libc.so.6
#1  0x00007ffff7ac3ef9 in PyUnicodeUCS4_FromString () from /lib64/libpython2.7.so.1.0
#2  0x00000000004645df in pybind11::str::str (this=<optimized out>, c=<optimized out>)
    at /usr/include/python2.7/pybind11/pytypes.h:899
#3  0x000000000047095a in pybind11::detail::object_api<pybind11::detail::accessor<pybind11::detail::accessor_policies::str_attr> >::operator[] (this=<optimized out>, key=<optimized out>)
    at /usr/include/python2.7/pybind11/pytypes.h:1409
#4  0x000000000046daf7 in main (argc=1, argv=0x7fffffffd9a8) at TestExc.cxx:33
```

**Comment by pavelschon** [comment]
My mistake. With the following line, it works as expected.
```c++
auto args = py::tuple(e.value().attr("args"));
```
