### ISSUE TITLE
Numpy structured arrays 

### ISSUE THREAD

**Issue by m4ce** [pybind/pybind11#2091]
Take the following example:

```c++
struct Bar {
  double a;
  double b;
};

struct Foo {
  int a;
  double b;
  std::array<Bar, 10> c;
};

PYBIND11_MODULE(libtest, m) {
  PYBIND11_NUMPY_DTYPE(Bar, a, b);
  PYBIND11_NUMPY_DTYPE(Foo, a, b, c);

  m.def("create_array", []() -> py::array {
      auto arr = py::array_t<Foo>(1);
      auto req = arr.request();
      auto ptr = static_cast<Foo *>(req.ptr);
      ptr[0].a = 10;
      ptr[0].b = 0.1;
      return std::move(arr);
      });
}
```

When calling `create_array()` from python:

```
>>> import libtest
>>> import pandas as pd
>>> d = libtest.create_array()
>>> d
array([(10, 0.1, [(5.43472210e-323, 1.32814727e-319), (0.00000000e+000, 0.00000000e+000), (2.13377005e-314, 2.13234436e-314), (3.95252517e-323, 3.95252517e-323), (1.26490687e-319, 0.00000000e+000), (0.00000000e+000, 2.13377192e-314), (2.13234436e-314, 7.90505033e-323), (7.90505033e-322, 1.21149147e+286), (1.84056692e-027, 6.17582057e-322), (2.22103644e-314, 1.52974041e-308)])],
      dtype={'names':['a','b','c'], 'formats':['<i4','<f8',([('a', '<f8'), ('b', '<f8')], (10,))], 'offsets':[0,8,16], 'itemsize':176})
>>> d.shape
(1,)
```

All good so far. I get my structured array. However, I am unable to figure out how to load that properly into a pandas DataFrame. If the array was a recarray, it'd be quite straight-forward. It seems the problem lies with the fact that it's one big tuple. Any way to drop that?

```
>>> import pandas as pd
pd>>> pd.DataFrame.from_records(d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 1311, in from_records
    mgr = _arrays_to_mgr(arrays, arr_columns, result_index, columns)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 7359, in _arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 7669, in _homogenize
    raise_cast_failure=False)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/series.py", line 4165, in _sanitize_array
    raise Exception('Data must be 1-dimensional')
Exception: Data must be 1-dimensional
>>> pd.DataFrame.from_records([d])
                                                   0
0  [10, 0.1, [[9e-323, 0.0], [0.0, 0.0], [0.0, 0....
```

Ideally, I'd want to load the data correctly with the column names too.

Thank you!

**Comment by m4ce** [comment]
Btw, if I drop the nested std::array, I can then load the numpy array into a dataframe..

The only alternative I found is this:

```
struct Foo {
  int a;
  double b;
  double ca0;
  double cb0;
  double ca1;
  double cb1;
  ...
};

PYBIND11_MODULE(libtest, m) {
  PYBIND11_NUMPY_DTYPE_EX(Foo, a, "a", b, "b", ca0, "c_a_0", "cb0", "c_b_0", ca1, "c_a_1", cb1, "c_b_1", ...);
```

is there a way to use the nested std::array without having to then copying in order to flatten the structure etc.?
