### ISSUE TITLE
Missing argument error messages should match python's

### ISSUE THREAD

**Issue by virtuald** [pybind/pybind11#2109]
## Issue description

When a user neglects to provide the correct number of arguments, pybind11 gives a different error message than that which python users might expect. In my opinion, the python error message is clearer.

## Reproducible example code

```c++
int add(int i, int j) {
    return i + j;
}
```
```py
def pyadd(i, j):
    return i + j
```

So if I call the python snippet:
```
>>> pyadd(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: pyadd() missing 1 required positional argument: 'j'
```

Whereas the pybind11 snippet is:

```
>>> add(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: add(): incompatible function arguments. The following argument types are supported:
    1. (i: int, j: int) -> int

Invoked with: 1
```

Now, this isn't a great example because the types are really short. But as a user, the first thing that I'm scanning for is the types and whether my types match -- it takes some effort to figure out the number is incorrect. Here's a more real example from pybind11:

```
Traceback (most recent call last):
  File "C:\Users\first\AppData\Local\Programs\Python\Python38\lib\site-packages\wpilib\_impl\start.py", line 106, in start
    self.robot.startCompetition()
  File "robot.py", line 84, in teleopPeriodic
    self.drive.arcadeDrive(self.trig, self.con0.getX())
TypeError: getX(): incompatible function arguments. The following argument types are supported:
    1. (self: wpilib._wpilib.XboxController, hand: wpilib.interfaces._interfaces.GenericHID.Hand) -> float

Invoked with: <wpilib._wpilib.XboxController object at 0x0000022286350F30>
```

There's a lot of punctuation in that error message, and the actual issue (missing argument) is obscured by everything. This gets worse as the number of arguments increases.

**Comment by bstaletic** [comment]
I'm not sure about this. If pybind matches python's format, the type information is lost. Considering that we're talking C++, type information is important.

**Comment by YannickJadoul** [comment]
The reason pybind11 gives this error message, is because it's also doing overload resolution, I think. This becomes clearer if you would bind both `int add(int, int)` and some (hypothetical) `std::string add(std::string)`; then pybind11 doesn't know if you missed a second argument or passed the wrong type for the argument.

But if you have a suggestion to change these error message that takes all of these possibilities into account (and can be implemented reasonably straightforwardly), we could definitely consider and discuss it further!

**Comment by virtuald** [comment]
I think the specific piece I would like to remove when possible is the "incompatible function arguments" message, as it's not particularly meaningful. It seems like it should be possible to detect specific badness, and when that badness occurs replace the generic "incompatible function arguments" message with a useful message instead.

For example, if the number of passed in arguments does not match the number of any of the overloads:

```
>>> add(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: add(): missing 1 required positional argument: 'j'. The following argument types are supported:
    1. (i: int, j: int) -> int

Invoked with: 1
```

Or in the more complex example:

```
Traceback (most recent call last):
  File "C:\Users\first\AppData\Local\Programs\Python\Python38\lib\site-packages\wpilib\_impl\start.py", line 106, in start
    self.robot.startCompetition()
  File "robot.py", line 84, in teleopPeriodic
    self.drive.arcadeDrive(self.trig, self.con0.getX())
TypeError: getX(): missing 1 required positional argument 'hand'. The following argument types are supported:
    1. (self: wpilib._wpilib.XboxController, hand: wpilib.interfaces._interfaces.GenericHID.Hand) -> float

Invoked with: <wpilib._wpilib.XboxController object at 0x0000022286350F30>
```

There are probably other categories of badness that could specifically be detected, though I'm not sure of the difficulty nor have I looked to see what pybind11 does when they occur:

* Invalid keyword argument
* Missing required keyword arguments

**Comment by YannickJadoul** [comment]
> For example, if the number of passed in arguments does not match the number of any of the overloads:

This would really add some overhead, to check these kinds of things, going over cases to see if they all mismatch the amount of parameters. And how would you then distinguish between too few or too many arguments (suppose you pass 1 argument, but you have an overload with 0 or 2 parameters?).

> Or in the more complex example:

Same here: what about if you have an overload that could also take `foot: wpilib.interfaces._interfaces.GenericHID.Foot` as second argument?

If you have a single function without overloads, sure, things can probably be made easier, but they would also become more inconsistent vs. the overloaded case?

Have a look at how the current code trying conversions and matching overloads looks:

https://github.com/pybind/pybind11/blob/0d70f0e18eec60786499faba53de4d72583ba2f7/include/pybind11/pybind11.h#L450-L812

I think a proposal for clearer error messages would definitely be appreciated, if this doesn't impede performance. But I'd like to see a more concrete proposal, that doesn't just fix a simple case, but takes the current complexity into account.

Do you feel like you would like to look deeper into this, and make a proposal on when exactly to show which error messages?  (That doesn't immediately need to be a complete pull request, as far as I'm concerned, but we'd need to see something more than just a wishlist, given the complexity of this `dispatcher` and the fact that this is a performance-critical part of pybind11.)

**Comment by virtuald** [comment]
I think the work for determining the error message could be deferred to after the error has been detected. Since an error has already occurred, it seems perfectly reasonable to add additional overhead at that point (as is currently the case when it's building the various function signatures for the error message). 

I can take a look at this, perhaps this weekend.
