### ISSUE TITLE
Assertion Error in threading module when finalize_interpreter

### ISSUE THREAD

**Issue by abidrahmank** [pybind/pybind11#2197]
## Reproducible example code

Standalone setup is provided here : https://gist.github.com/abidrahmank/1ec549e13f600cd11eb70561c9223210

Just call `make`

## Issue description
I have following workflow :

* I have a C library (**crashloader.cpp**) which will load other shared library plugins (**threadcrash.cpp**) and execute functions in that.

* Plugin libraries typically contains a function that creates an object (**goo**), execute it (**execgoo**) and delete it (**delgoo**).

* In my case, plugin embeds a Python script and execute it. So I initialize interpreter in object constructor and finalize it in destructor.

**Issue :** Everything works fine if I call exec in the same thread as creating the object. But the moment I call exec in a separate thread (which is my actual use case), I get following Assertion Error.

``` sh
Exception ignored in: <module 'threading' from '......../lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "......./lib/python3.6/threading.py", line 1299, in _shutdown
    assert tlock.locked()
AssertionError:  
```

**Comment by abidrahmank** [comment]
**More data points**
1. Assertion Error happens only when `threading` module is imported (either directly or indirectly via numpy import etc.)

**Comment by abidrahmank** [comment]
**One more data point**

1. After further testing, I noticed that, if I import threading module immediately after `py::initialize_interpreter` in **threadcrash.cpp**, then it works fine.

``` cpp
/*updated threadcrash.cpp line:20*/
pybind11::initialize_interpreter()
py::module::import("threading");
// This also works : py::exec("import threading; print(threading._main_thread)");
```

**Comment by msardonini** [comment]
I also have this problem. Here is a quick way to reproduce it.

```c++
#include <thread>

#include "pybind11/embed.h"

namespace py = pybind11;

void test_func() {
  py::gil_scoped_acquire acquire;
  auto module = py::module_::import("numpy");  // Throws exception
  // auto module = py::module_::import("sys");  // does not throw expction
  // auto module = py::module_::import("threading");  // throws
}

int main() {
  py::scoped_interpreter guard;  // Python exception thrown in destructor of 'guard'
  py::gil_scoped_release release;
  {
    std::thread my_thread = std::thread(test_func);
    my_thread.join();
  }
}

```

I see the output:
```
Exception ignored in: <module 'threading' from '/app/.pyenv/versions/3.8.10/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/app/.pyenv/versions/3.8.10/lib/python3.8/threading.py", line 1373, in _shutdown
    assert tlock.locked()
AssertionError:
```


Is there something we should be doing at the end of the thread before `module` is destroyed? Can someone provide some context on what the problem is here?

Any help is appreciated,

**Comment by maplelost** [comment]
> **One more data point**
> 
> 1. After further testing, I noticed that, if I import threading module immediately after `py::initialize_interpreter` in **threadcrash.cpp**, then it works fine.
> 
> ```c++
> /*updated threadcrash.cpp line:20*/
> pybind11::initialize_interpreter()
> py::module::import("threading");
> // This also works : py::exec("import threading; print(threading._main_thread)");
> ```

You truly save my day.Thx

**Comment by moratom** [comment]
@msardonini did you by any chance find any solutions for this? I'm also running into the same issue.
