### ISSUE TITLE
(deep)copy doesn't work on Python2

### ISSUE THREAD

**Issue by MatthijsBurgh** [pybind/pybind11#2208]
##  Issue description
Both `copy` and `deepcopy` throw a `TypeError` in Python 2.
```
Traceback (most recent call last):
  File "/home/travis/build/orocos/orocos_kinematics_dynamics/python_orocos_kdl/tests/framestest.py", line 436, in testCopy
    self.testCopyImpl(copy)
  File "/home/travis/build/orocos/orocos_kinematics_dynamics/python_orocos_kdl/tests/framestest.py", line 419, in testCopyImpl
    v2 = copy(v1)
  File "/usr/lib/python2.7/copy.py", line 96, in copy
    return _reconstruct(x, rv, 0)
  File "/usr/lib/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/usr/lib/python2.7/copy_reg.py", line 93, in __newobj__
    return cls.__new__(cls, *args)
TypeError: pybind11_object.__new__(PyKDL.Vector) is not safe, use object.__new__()
```
(https://travis-ci.org/github/orocos/orocos_kinematics_dynamics/jobs/686926468#L1035)

There are no issues with Python 3. In the documentation nothing is mentioned about (deep)copy. Should this work out of the box like it does on Python 3? Should the user implement his own custom `__deepcopy__` methods?

## Reproducible example code
Binding code of the `Vector` is here: https://github.com/orocos/orocos_kinematics_dynamics/blob/master/python_orocos_kdl/PyKDL/pybind11/frames.cpp
C++ code of the `Vector` is here: https://github.com/orocos/orocos_kinematics_dynamics/blob/master/orocos_kdl/src/frames.hpp#L160
I refer here to `Vector`, as it one of the simplest classes, but the problem happens at all classes in the module.

**Comment by MatthijsBurgh** [comment]
Problem was the copy module can use the pickle functions to create a (deep)copy. But on Python2 the normal pickle module is not supported, only CPickle. Therefore it did work on Python3 but not on Python2. (The classes in my example are pickable)

Solution is to add custom `__copy__` and `__deepcopy__` methods. Which will also improve performance. Added to documentation in #2242.
