### ISSUE TITLE
Scoped enums and arithmetic

### ISSUE THREAD

**Issue by Trigve** [pybind/pybind11#2221]
## Issue description

`arithmetic` isn't working for scoped enums.

## Reproducible example code

If I have
`enum_<ScopedEnum>(m, "ScopedEnum", arithmetic{})`
`.value("Value1", ScopedEnum::Value1)`
`...`

then in python
`
ScopedEnum.Value1 | ScopedEnum.Value1
`
it throws error  `unsupported operand type(s) for |: 'int' and 'ScopedEnum'`

The problem is in `enum_` class, where the arithmetic operations are defined only for `is_convertible` types. But scoped enums arent implicitely convertible. But if I explicitly specify the `arithmetic` it should treat it as convertible.  
So changing
`constexpr bool is_convertible = std::is_convertible<Type, Scalar>::value;`
to
`constexpr bool is_convertible = is_arithmetic || std::is_convertible<Type, Scalar>::value;`

does solve the problem.

**Comment by axxel** [comment]
I ran into the same (or almost the same) issue. My use case is
```python
ScopedEnum.Value2 | ScopedEnum.Value3
```

And the error: `unsupported operand type(s) for |: 'ScopedEnum' and 'ScopedEnum'`

**Comment by Trigve** [comment]
The quick fix is to add
`PYBIND11_ENUM_OP_STRICT("__or__", int_(a) | int_(b), PYBIND11_THROW);`
`PYBIND11_ENUM_OP_STRICT("__ror__", int_(a) | int_(b), PYBIND11_THROW);`

on the "else" case for "is_convertible" (around line 1515) in pybind11.h

**Comment by YannickJadoul** [comment]
This is probably by design. It would not work for `enum class` in C++ either, so it does not really make sense to export these operators by default, I think?

If you need them, you can still manually define these methods on the `enum_` object?

**Comment by bstaletic** [comment]
An alternative is to use `.def()` on the `enum_` itself to add `__xor__()` to scoped enums.

**Comment by axxel** [comment]
> This is probably by design. It would not work for `enum class` in C++ either, so it does not really make sense to export these operators by default, I think?

The 'official' c++ approach seems to be a custom `operator|`, which is what I did. Now I thought specifying the `arithmetic` tag is exactly supposed to manually/specifically request that operator on the python side?

I can certainly provide an extra `.def()` to make it work but then it would be nice if the [documentation](https://pybind11.readthedocs.io/en/stable/classes.html#enumerations-and-internal-types) mentioned that somehow.

Speaking of documentation, I'm new to this. Anyone care to spell out the `.def()` line for the '|' operator?

**Comment by bstaletic** [comment]
> Speaking of documentation, I'm new to this. Anyone care to spell out the .def() line for the '|' operator?

```c++
py::enum_<E>(m, "E").value("E1", E::E1).def("__xor__", [](E e1, E other){ return int(e1) | int(e2); });
```

You likely want to specify `__rxor__` too, with inverted arguments. Also consider an `__xor__`/`__rxor__` pair for something like `py::int_`.

Alternatively, just one `__xor__`/`__rxor__` pair that takes `py::object` and then manually check what it is with a series of `if(py::isinstance<py_type>(other))`.

**Comment by YannickJadoul** [comment]
> The 'official' c++ approach seems to be a custom `operator|`, which is what I did. Now I thought specifying the `arithmetic` tag is exactly supposed to manually/specifically request that operator on the python side?

`py::arithmetic` only provides comparison/ordering operators in case of `enum class`, I believe. Otherwise, you'd need a non-scoped/default `enum`.

> ```c++
> py::enum_<E>(m, "E").value("E1", E::E1).def("__xor__", [](E e1, E other){ return int(e1) | int(e2); });
> ```

If you have the custom operator as free-standing function, this might be even better:

```
py::enum_<E>(m, "E")
    .value("E1", E::E1)
    .def("__xor__", py::overload_cast<E, E>(&operator|));
```

> I can certainly provide an extra `.def()` to make it work but then it would be nice if the [documentation](https://pybind11.readthedocs.io/en/stable/classes.html#enumerations-and-internal-types) mentioned that somehow.

I agree, sometimes the docs are a bit lacking or outdated. Any PR here is probably welcomed by the maintainers.

**Comment by Trigve** [comment]
> 
> 
> This is probably by design. It would not work for `enum class` in C++ either, so it does not really make sense to export these operators by default, I think?
> 

I don' agree. The goal of Pybind11 isn't emulating C++ in python. If I export C++ enum to python I want to behave as python enum not as in implementation language (C++ here). No matter if the enum is scoped or not. All I want is to behave as python enum. Therefor if I specify the enum as `arithmetic` I'm explicitly telling the system that I want to treat it as python enum.

**Comment by YannickJadoul** [comment]
Alright, let's put it differently, then: pybind11 is not stopping you from doing this (see comments about using `.def` above), but decides is probably the wrong default, even with `py::arithmetic`. If C++ doesn't allow you to apply bit-operations to `enum class`es by default (`enum class` doesn't just add scope, but also gets rid of implicit conversions and turns an iteration into a full type), and someone made the choice to use an `enum class` and not just an `enum` as part of a C++ interface, then it would be bad behavior from pybind11 to violate this contract/choice implicitly. You might not want to emulate a C++ interface, but you still want to respect it.

Note that `py::arithmetic` still does something: it adds comparison operators `<`, `>`, `<=` and `>=`, so the option is not fully ignored.

Should it be documented better: definitely. But it's also just a convenience thing that you can write yourself if you want.

But I'm not a maintainer of this, so feel free to make a PR and fix this. I'm just explaining a possible reason why this decision was probably made.

>  All I want is to behave as python enum.

Trying the example from the Python docs, you can't do bit operations on `Enum`s either:

```pycon
>>> from enum import Enum
>>> class Color(Enum):
...     RED = 1
...     GREEN = 2
...     BLUE = 3
... 
>>> Color
<enum 'Color'>
>>> Color.RED
<Color.RED: 1>
>>> Color.RED | Color.GREEN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'Color' and 'Color'
>>> 
```

**Comment by Trigve** [comment]
> 
> 
> Alright, let's put it differently, then: pybind11 is not stopping you from doing this (see comments about using `.def` above), but decides is probably the wrong default, even with `py::arithmetic`. If C++ doesn't allow you to apply bit-operations to `enum class`es by default (`enum class` doesn't just add scope, but also gets rid of implicit conversions and turns an iteration into a full type), and someone made the choice to use an `enum class` and not just an `enum` as part of a C++ interface, then it would be bad behavior from pybind11 to violate this contract/choice implicitly. You might not want to emulate a C++ interface, but you still want to respect it.
> 

Of course. This is handled by "wrapper" classes/function when you can do checks, etc.. Anyway, I can't think of any example that would allow bogus code to compile but would like to see one how it behave.

> Note that `py::arithmetic` still does something: it adds comparison operators `<`, `>`, `<=` and `>=`, so the option is not fully ignored.
> 
> Should it be documented better: definitely. But it's also just a convenience thing that you can write yourself if you want.
> 

Yes, the documentation (Not great, not terrible) lack info that `arithmetic` is doing something different for scoped enums.
But you need to write it for all enums, which means code duplication and/or therefor more complex code.

> But I'm not a maintainer of this, so feel free to make a PR and fix this. I'm just explaining a possible reason why this decision was probably made.
> 

Before doing PR I would like to discuss and find the best possible solution, that will be flexible and also enforce the code correctness.

> > All I want is to behave as python enum.
> 
> Trying the example from the Python docs, you can't do bit operations on `Enum`s either:
> 
> ```
> >>> from enum import Enum
> >>> class Color(Enum):
> ...     RED = 1
> ...     GREEN = 2
> ...     BLUE = 3
> ... 
> >>> Color
> <enum 'Color'>
> >>> Color.RED
> <Color.RED: 1>
> >>> Color.RED | Color.GREEN
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> TypeError: unsupported operand type(s) for |: 'Color' and 'Color'
> >>> 
> ```

This could be fixed in python inheriting from `IntFlag`. In pybind11, there isn't any such "tag", the most similar one is `arithmetic` tag. So the quick fix could be to add it there.

The better one would be to make a new tag like `int_flag` that would implement `|` operator.
