### ISSUE TITLE
ImportError: No module named __builtins__

### ISSUE THREAD

**Issue by pavelschon** [pybind/pybind11#2339]
## Issue description

It is not possible to import `__builtins__`.
The error which is thrown is:
```
ImportError: No module named __builtins__
```

## Reproducible example code
```c++
const auto builtins_module = py::module::import("__builtins__");
const auto hex_func = builtins_module.attr("hex");
```
Note that the above code works in _BoostPython_.

**Comment by bstaletic** [comment]
```
bstaletic@Gallifrey YouCompleteMe  (git)-[nopy35]-% python
Python 3.8.4 (default, Jul 15 2020, 11:39:45)
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import __builtins__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named '__builtins__'
>>>
bstaletic@Gallifrey YouCompleteMe  (git)-[nopy35]-% python2
Python 2.7.18 (default, Apr 24 2020, 07:39:17)
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import __builtins__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named __builtins__
>>>
```

`__builtins__` is not anything standard. If you are on python3, you can `import("builtins");`.

**Comment by YannickJadoul** [comment]
@pavelschon, so your Boost.Python code used Python 2, then?

**Comment by pavelschon** [comment]
I'm sorry, this was a user error (my).
In python 2, it is `__builtin__` -> works.
In python 3, it is `builtin` -> works.
