### ISSUE TITLE
Segfault on binding static method as instance method

### ISSUE THREAD

**Issue by phtown** [pybind/pybind11#2495]
## Issue
Listing argument names for a static method leads to an error having to do with the number of arguments. This works fine for bound methods.

## Example code
I have the following files:
`example1.cc`
```
#include <pybind11/pybind11.h>

namespace py = pybind11;

class Example {
public:
  static Example Foo(double f1, double f2);
};

PYBIND11_MODULE(example, m) {
  py::class_<Example>(m, "Example")
      .def("Foo", &Example::Foo, "Example function", py::arg("f1"));
}
```
`example2.cc`
```
#include <pybind11/pybind11.h>

namespace py = pybind11;

class Example {
public:
  static Example Foo(double f1, double f2);
};

PYBIND11_MODULE(example, m) {
  py::class_<Example>(m, "Example")
      .def("Foo", &Example::Foo, "Example function", py::arg("f1"), py::arg("f2"));
}
```

Note the difference on line 12. Compiling `example1.cc` leads to no errors. Compiling `example2.cc` leads to the following error:
```
In file included from example2.cc:1:0:
/home/htown/.local/lib/python3.6/site-packages/pybind11/include/pybind11/pybind11.h: In instantiation of ‘void pybind11::cpp_function::initialize(Func&&, Return (*)(Args ...), const Extra& ...) [with Func = Example (*&)(double, double); Return = Example; Args = {double, double}; Extra = {pybind11::name, pybind11::is_method, pybind11::sibling, char [17], pybind11::arg, pybind11::arg}]’:
/home/htown/.local/lib/python3.6/site-packages/pybind11/include/pybind11/pybind11.h:64:9:   required from ‘pybind11::cpp_function::cpp_function(Return (*)(Args ...), const Extra& ...) [with Return = Example; Args = {double, double}; Extra = {pybind11::name, pybind11::is_method, pybind11::sibling, char [17], pybind11::arg, pybind11::arg}]’
/home/htown/.local/lib/python3.6/site-packages/pybind11/include/pybind11/pybind11.h:1118:22:   required from ‘pybind11::class_<type_, options>& pybind11::class_<type_, options>::def(const char*, Func&&, const Extra& ...) [with Func = Example (*)(double, double); Extra = {char [17], pybind11::arg, pybind11::arg}; type_ = Example; options = {}]’
example2.cc:12:82:   required from here
/home/htown/.local/lib/python3.6/site-packages/pybind11/include/pybind11/pybind11.h:133:9: error: static assertion failed: The number of argument annotations does not match the number of function arguments
         static_assert(expected_num_args<Extra...>(sizeof...(Args), cast_in::has_args, cast_in::has_kwargs),
         ^~~~~~~~~~~~~
/home/htown/.local/lib/python3.6/site-packages/pybind11/include/pybind11/pybind11.h:137:19: error: cannot convert ‘pybind11::cpp_function::initialize(Func&&, Return (*)(Args ...), const Extra& ...) [with Func = Example (*&)(double, double); Return = Example; Args = {double, double}; Extra = {pybind11::name, pybind11::is_method, pybind11::sibling, char [17], pybind11::arg, pybind11::arg}]::<lambda(pybind11::detail::function_call&)>’ to ‘pybind11::handle (*)(pybind11::detail::function_call&)’ in assignment
         rec->impl = [](function_call &call) -> handle {

```

**Comment by phtown** [comment]
And by "no errors" I mean I just realized `example1.cc` compiles but Python throws a segfault when I try to import the module.

**Comment by bstaletic** [comment]
For static member functions, there's `py::module::def_static()`.

**Comment by YannickJadoul** [comment]
> And by "no errors" I mean I just realized `example1.cc` compiles but Python throws a segfault when I try to import the module.

@bstaletic A segfault here seems problematic, though?

**Comment by YannickJadoul** [comment]
I can reproduce the segfault. Reopening and renaming the issue.

**Comment by bstaletic** [comment]
@YannickJadoul A segfault here should be expected.

In the above example, `self` gets passed in and reinterpreted as `double` and `f1` gets reinterpreted as `f2`.

**Comment by YannickJadoul** [comment]
@bstaletic But already on import? And to be fair, I though `.def("Foo", &Example::Foo, "Example function", py::arg("f1"));` already wouldn't compile?

**Comment by bstaletic** [comment]
For the record, I can't repro the segfault.

**Comment by YannickJadoul** [comment]
@phtown, for me, this is happening:

```
>>> sys.excepthook
<function apport_excepthook at 0x7f915d874730>
>>> sys.excepthook = sys.__excepthook__
>>> sys.excepthook
<built-in function excepthook>
>>> import example
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/yannick/tmp/sandbox/build/example.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN7Example3FooEdd
```

(but the default `apport_excepthook` somehow crashes; I'm not sure how or why, but that's definitely not pybind11's fault)

**Comment by YannickJadoul** [comment]
Fixing that undefined symbol by giving `Example::Foo` a definition makes things crash as expected for me:

```pycon
>>> import example
>>> example.Example.Foo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Foo(): incompatible function arguments. The following argument types are supported:
    1. (self: float, f1: float) -> example.Example

Invoked with: 
>>> 
```
