### ISSUE TITLE
How to create a type alias of a vector<T>?

### ISSUE THREAD

**Issue by mavam** [pybind/pybind11#317]
I'm looking for a method to construct a simple type alias, which I couldn't find explained in the manual/examples.

Say I have `std::vector<T>`, how can I register it in my module named `foo` under the name `foo.Vector`? This didn't work for me:

```cpp
  py::class_<std::vector<T>>(m, "Vector")
    .def(py::init<>());
```

When I try to call `foo.Vector([])`, I get this error:
```
TypeError: Incompatible function arguments. The following argument types are supported:
    1. (list<foo.T>) -> NoneType
     Invoked with: <foo.Vector object at 0x10ea1c688>, []
```

(Type `T` is just a placeholder for another type announced via `py::class_<T>(m, "...")`.)

**Comment by wjakob** [comment]
It's all in the documentation ("opaque types")

**Comment by mavam** [comment]
So that means I have to duplicate all of the code in `stl_bind.h` if I want a reasonable vector interface?

**Comment by wjakob** [comment]
If you want to roll your own, yes

**Comment by mavam** [comment]
I just want to inject a specific vector instance (say `std::vector<int>`) under a specific symbol name (say `Vector`) in my module, without having to roll my own duplicated `std::vector` pybind interface. Is that somehow possible?

**Comment by wjakob** [comment]
Why don't you use stl_bind then?

**Comment by mavam** [comment]
I want to, I just don't know how the syntax looks like. This is what I'm looking for:

```cpp
  py::module m{"foo", "..."};
  py::alias<std::vector<int>>(m, "Vector"); // Allows me to use foo.Vector with all existing methods.
```

**Comment by wjakob** [comment]
Please take a look at the examples directory which has a testcase for stl_bind

**Comment by mavam** [comment]
Okay, so for vector there exists a custom solution: `py::bind_vector<unsigned int>(m, "VectorInt");`. How about adapters for `std::set` and `std::table`?

**Comment by wjakob** [comment]
std::vector is the only one with official bindings at the moment, and there is a PR in the queue for map. Other external contributions are welcomed. I have never heard of std::table.

**Comment by mavam** [comment]
My bad, I meant `std::map` (which translates to a type `table` type in my Python bindings). I'll see if I can get started with the code in PR.

**Comment by mavam** [comment]
FWIW, I'm getting an infinite recursion with `py::bind_vector<T>`:

```
==26412==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x00010c0db55d bp 0x7fff571bcc30 sp 0x7fff571bcb60 T0)
==26412==atos returned: An admin user name and password is required to enter Developer Mode.
    #0 0x10c0db55c in pybind11::str::operator std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >() const (..broker/_broker.so+0x6755c)
    #1 0x10c0dd6fd in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) (..broker/_broker.so+0x696fd)
    #2 0x109753c63 in PyCFunction_Call (/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/Python+0x42c63)
    #3 0x10971ae81 in PyObject_Call (/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/Python+0x9e81)
    #4 0x10972d667 in method_call (/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/Python+0x1c667)
    #5 0x10971ae81 in PyObject_Call (/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/Python+0x9e81)
    #6 0x1097ba80b in PyEval_CallObjectWithKeywords (/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/Python+0xa980b)
    #7 0x1097653ff in slot_tp_repr (/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/Python+0x543ff)
    #8 0x109755b47 in PyObject_Str (/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/Python+0x44b47)
    #9 0x10c0dd6d4 in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) (..broker/_broker.so+0x696d4)
    #10 0x109753c63 in PyCFunction_Call (/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/Python+0x42c63)
    #11 0x10971ae81 in PyObject_Call (/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/Python+0x9e81)
    #12 0x10972d667 in method_call (/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/Python+0x1c667)
    #13 0x10971ae81 in PyObject_Call (/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/Python+0x9e81)
    #14 0x1097ba80b in PyEval_CallObjectWithKeywords (/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/Python+0xa980b)
    #15 0x1097653ff in slot_tp_repr (/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/Python+0x543ff)
    #16 0x109755b47 in PyObject_Str (/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/Python+0x44b47)
    #17 0x10c0dd6d4 in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) (..broker/_broker.so+0x696d4)
...
```

I've narrowed it down to `detail::vector_if_insertion_operator<Vector, Class_>(cl, name);`. When I comment this statement, it works just fine. That is, somehow in the definition of `__repr__` something goes wrong:

```cpp
    cl.def("__repr__",
           [name](Vector &v) {
            std::ostringstream s;
            s << name << '[';
            for (size_type i=0; i < v.size(); ++i) {
                s << v[i];
                if (i != v.size() - 1)
                    s << ", ";
            }
            s << ']';
            return s.str();
        },
        "Return the canonical string representation of this list."
    );
```

I don't see anything peculiar in the above code, so at this point I'm puzzled what's going on behind the scenes. I can try to narrow it down to a self-contained example, if you don't have hunch based on the stack trace.

**Comment by wjakob** [comment]
Can you post a self-contained example in a new ticket?
