### ISSUE TITLE
[BUG]: Smart holder branch doesn't work with trampoline class

### ISSUE THREAD

**Issue by danielcjacobs** [pybind/pybind11#3927]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

I've been trying to get around issues related to #3262 (`tried to call pure virtual function` error when python releases ownership of a bound object), and I came across the [smart holder branch](https://github.com/pybind/pybind11/blob/smart_holder/README_smart_holder.rst).

I attempted to use the `Progressive` mode to solve the problem with my trampoline class, but it didn't fix anything.

I have a trampoline class for `Foo`, which holds a reference to a `Bar` object. If I try to extend Foo in python, I can't let python release its reference to the `Bar` object, else I will get a `tried to call pure virtual function` error when trying to access the Bar object.

The smart holder branch seems intended to solve this very issue. I did the following:
- Added `-DPYBIND11_USE_SMART_HOLDER_AS_DEFAULT` to compilation commands
- Replaced `std::shared_ptr<...>` holder with `PYBIND11_SH_DEF(Foo)`
- Inherit trampoline class from `public py::trampoline_self_life_support`

*Note*: when I compile, I get this warning:
```
warning: ‘PyFoo’ declared with greater visibility than its base ‘pybind11::trampoline_self_life_support’ [-Wattributes]
  134 | class PyFoo : Foo, py::trampoline_self_life_support {
```
And when I run (with or without smart holder branch), I get this error:
```
Traceback (most recent call last):
  File "pybind_test.py", line 26, in <module>
    main()
  File "pybind_test.py", line 22, in main
    print(bar2.call_increment(input))
RuntimeError: Tried to call pure virtual function "Foo::increment"
```

### Reproducible example code

```text
// C++
#include <pybind11/pybind11.h>

class Foo {
public:
	virtual ~Foo()                   = default;
	virtual int increment(int input) = 0;
};

class Bar {
public:
	std::shared_ptr<Foo> stored_foo;

	void add_foo(std::shared_ptr<Foo> foo) { stored_foo = foo; }

	int call_increment(int input) { return stored_foo->increment(input); }
};

// Trampoline class
class PyFoo : Foo, public py::trampoline_self_life_support {
public:
	using Foo::Foo;

	int increment(int input) override { PYBIND11_OVERLOAD_PURE(int, Foo, increment, input) }
};

// Bindings
py::class_<Foo, PyFoo, PYBIND11_SH_DEF(Foo)>(m, "Foo")
	.def(py::init<>())
	.def("increment", &Foo::increment);

py::class_<Bar>(m, "Bar")
	.def(py::init<>())
	.def("add_foo", &Bar::add_foo)
	.def("call_increment", &Bar::call_increment);


# pybind_test.py, includes MyFoo derived from Foo
#!/usr/bin/env python3

import Foo, Bar

class MyFoo(Foo):
    def increment(self, input):
        return input + 1


def main():
    foo = MyFoo()
    input = 5
    bar = Bar()
    bar.add_foo(foo)
    print(bar.call_increment(input)) # Works

    bar2 = Bar()
    bar2.add_foo(MyFoo())
    print(bar2.call_increment(input)) # Fails


if __name__ == '__main__':
    main()
```

**Comment by danielcjacobs** [comment]
hmm..... it works if I add a `public` modifier before `Foo` here:
```cpp
class PyFoo : _public_ Foo, public py::trampoline_self_life_support {
```
Note, the warning about visibility is still there

**Comment by Skylion007** [comment]
Ping @rwgk

**Comment by rwgk** [comment]
> tried to call pure virtual function
> The smart holder branch seems intended to solve this very issue.

Only if there is actually a lifetime issue (with pybind11 master), but not in general. It looks like your case is in the "general" domain. 

> warning: ‘PyFoo’ declared with greater visibility than its base ‘pybind11::trampoline_self_life_support’ [-Wattributes]
  134 | class PyFoo : Foo, py::trampoline_self_life_support {

This seems to be related:

https://stackoverflow.com/questions/2828738/c-warning-declared-with-greater-visibility-than-the-type-of-its-field

With a lot of guessing, `PyFoo` seems to have default visibility, while `trampoline_self_life_support` has hidden visibility.

Spontaneous best guesses:
* Build your extension with -fvisibility=hidden (I think that's what the documentation recommends).
* Silence the warning if you cannot use -fvisibility=hidden.
* Or build everything with -fvisibility=default (that's what we do internally at Google).

Your milage may vary.

Or do you think we need to `PYBIND11_EXPORT` ‘trampoline_self_life_support’? (I hope not, but it totally depends, I guess.)

**Comment by danielcjacobs** [comment]
Seeing that it works without deriving from `py::trampoline_self_life_support`, I'm curious as to what the purpose of inheriting from this class is?

**Comment by danielcjacobs** [comment]
> Or do you think we need to PYBIND11_EXPORT ‘trampoline_self_life_support’? (I hope not, but it totally depends, I guess.)

I'm curious, why would we not export this symbol? Seems like it should be exported since it's intended to be used by other libraries.

**Comment by rwgk** [comment]
> Seeing that it works without deriving from `py::trampoline_self_life_support`, I'm curious as to what the purpose of inheriting from this class is?

Did you see this already?

https://github.com/pybind/pybind11/blob/smart_holder/README_smart_holder.rst#trampolines-and-stdunique_ptr

Takeaway:
* You only need it if you want to pass `unique_ptr`s between Python and C++.
* Best practice: Always use it (maybe with `#ifdef` if you want to stay compatible with master).

**Comment by rwgk** [comment]
> > Or do you think we need to PYBIND11_EXPORT ‘trampoline_self_life_support’? (I hope not, but it totally depends, I guess.)
> 
> I'm curious, why would we not export this symbol? Seems like it should be exported since it's intended to be used by other libraries.

I'm not sure to be honest, especially because we (Google) internally use "default" visibility, i.e. everything is exported.

I am thinking/guessing for the "external" world that does many things differently, keeping the symbol hidden is better, for situations in which extensions are built with different pybind11 versions, compilers, or options, or all of it.

**Comment by rwgk** [comment]
Unrelated to this issue, I recently got to understand more about `-fvisibility=hidden` and `namespace pybind11 __attribute__((visibility("hidden")))` (pybind11/detail/common.h).

My thinking now:

* Exporting `py::trampoline_self_life_support` is definitely not the right approach, because it could lead to issues if extensions built with different versions of pybind11 are used in the same process.
* With respect to the "declared with greater visibility" warning shown in the original posting, that can be resolved by marking the enclosing namespace with `__attribute__((visibility("hidden")))`, similar to (currently draft) PR #4072.
* An alternative is to use a `#pragma GCC diagnostic push, ignored, pop` around the trampoline class, to suppress the warning.
* Another more radical alternative is to `-DPYBIND11_NAMESPACE=pybind11`, which means all module-local features will be unavailable. That is probably only an option in tightly controlled environments, when it is certain that `RTLD_LOCAL` or equivalent is in effect, or that all extensions are built with the same pybind11 version.
