### ISSUE TITLE
Building recent Pybind11 master in debug result in 'ImportError: Could not allocate tuple object!'

### ISSUE THREAD

**Issue by lyskov** [pybind/pybind11#414]
Hi, i recently noticed that building my project in debug mode with recent Pybind11 master result in the following import error (below). The corresponding release build seems to run fine. I understand that this not very informative message so i am trying to isolate code that lead to this problem. In meanwhile i am posting here in case you might have an idea of what might be wrong.

Thank you,

```
Python 3.5.1 (default, Dec  7 2015, 11:00:08)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 903, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: Could not allocate tuple object!
```

**Comment by lyskov** [comment]
Never mind, looks like the problem was due to issues with #410 code. But due to failure of build system to track dependency it mitigated even for master branch. Sorry for the false alarm, i am closing this for now.
